### ISSUE TITLE
async preload data

### ISSUE THREAD

**Issue by hongnk** [matthoffner/snowpack-react-ssr#11]
I try this out and it works well, but not familiar with babel-ssr solution. How can I async preload data for SSR render? Thank you.

**Comment by matthoffner** [comment]
Hello, async preloading data can be added to the main app function. This function can be converted to async https://github.com/matthoffner/snowpack-react-ssr/blob/master/server/index.js#L16

This boilerplate is meant to be pretty minimal - something like Express or Koa with React Router would be the more standard way to handle routes and fetching data server side.

**Comment by hongnk** [comment]
Thanks. I was searching for way to preload data in jsx pages, something like what nextjs provides. But I guess it is not built-in. Will look at how to integrate router.
